### ISSUE TITLE
Is a web server required?

### ISSUE THREAD

**Issue by onlywei** [vitalets/mocha-es6-modules#2]
Hi @vitalets, I just cloned this repo and tried to open `index.html` in my browser. Everything failed because none of the javascript files were allowed to be downloaded due to CORS. I don't understand how this could be useful if I need to set up a web server in order to run the tests. How did you get around this?

**Comment by vitalets** [comment]
hi @onlywei! 

Yes, webserver is required to open page by `http://` protocol instead of `file://` (that has many restrictions).
Simple http-server is included into repo, so if you already cloned it there are a few steps to run it. I've added a [Run locally section](https://github.com/vitalets/mocha-es6-modules#run-locally) to readme.
